export const INDIA_CITIES = [
    { name: 'Agra', state: 'Uttar Pradesh' },
    { name: 'Ahmedabad', state: 'Gujarat' },
    { name: 'Ajmer', state: 'Rajasthan' },
    { name: 'Akola', state: 'Maharashtra' },
    { name: 'Aligarh', state: 'Uttar Pradesh' },
    { name: 'Allahabad', state: 'Uttar Pradesh' },
    { name: 'Alwar', state: 'Rajasthan' },
    { name: 'Ambala', state: 'Haryana' },
    { name: 'Amravati', state: 'Maharashtra' },
    { name: 'Amritsar', state: 'Punjab' },
    { name: 'Aurangabad', state: 'Maharashtra' },
    { name: 'Bangalore', state: 'Karnataka' },
    { name: 'Bareilly', state: 'Uttar Pradesh' },
    { name: 'Bathinda', state: 'Punjab' },
    { name: 'Belgaum', state: 'Karnataka' },
    { name: 'Bhavnagar', state: 'Gujarat' },
    { name: 'Bhilai', state: 'Chhattisgarh' },
    { name: 'Bhiwadi', state: 'Rajasthan' },
    { name: 'Bhiwandi', state: 'Maharashtra' },
    { name: 'Bhopal', state: 'Madhya Pradesh' },
    { name: 'Bhubaneswar', state: 'Odisha' },
    { name: 'Bikaner', state: 'Rajasthan' },
    { name: 'Bilaspur', state: 'Chhattisgarh' },
    { name: 'Bokaro', state: 'Jharkhand' },
    { name: 'Burdwan', state: 'West Bengal' },
    { name: 'Chandigarh', state: 'Punjab' },
    { name: 'Chennai', state: 'Tamil Nadu' },
    { name: 'Coimbatore', state: 'Tamil Nadu' },
    { name: 'Cuttack', state: 'Odisha' },
    { name: 'Dehradun', state: 'Uttarakhand' },
    { name: 'Delhi', state: 'Delhi' },
    { name: 'Dhanbad', state: 'Jharkhand' },
    { name: 'Durg', state: 'Chhattisgarh' },
    { name: 'Faridabad', state: 'Haryana' },
    { name: 'Firozabad', state: 'Uttar Pradesh' },
    { name: 'Gandhinagar', state: 'Gujarat' },
    { name: 'Ghaziabad', state: 'Uttar Pradesh' },
    { name: 'Goa', state: 'Goa' },
    { name: 'Gorakhpur', state: 'Uttar Pradesh' },
    { name: 'Gurugram', state: 'Haryana' },
    { name: 'Guwahati', state: 'Assam' },
    { name: 'Gwalior', state: 'Madhya Pradesh' },
    { name: 'Haldwani', state: 'Uttarakhand' },
    { name: 'Haridwar', state: 'Uttarakhand' },
    { name: 'Hisar', state: 'Haryana' },
    { name: 'Howrah', state: 'West Bengal' },
    { name: 'Hubli', state: 'Karnataka' },
    { name: 'Hyderabad', state: 'Telangana' },
    { name: 'Indore', state: 'Madhya Pradesh' },
    { name: 'Jabalpur', state: 'Madhya Pradesh' },
    { name: 'Jaipur', state: 'Rajasthan' },
    { name: 'Jalandhar', state: 'Punjab' },
    { name: 'Jamnagar', state: 'Gujarat' },
    { name: 'Jamshedpur', state: 'Jharkhand' },
    { name: 'Jhansi', state: 'Uttar Pradesh' },
    { name: 'Jodhpur', state: 'Rajasthan' },
    { name: 'Kakinada', state: 'Andhra Pradesh' },
    { name: 'Kanpur', state: 'Uttar Pradesh' },
    { name: 'Karnal', state: 'Haryana' },
    { name: 'Kharagpur', state: 'West Bengal' },
    { name: 'Kochi', state: 'Kerala' },
    { name: 'Kolhapur', state: 'Maharashtra' },
    { name: 'Kolkata', state: 'West Bengal' },
    { name: 'Kota', state: 'Rajasthan' },
    { name: 'Kozhikode', state: 'Kerala' },
    { name: 'Lucknow', state: 'Uttar Pradesh' },
    { name: 'Ludhiana', state: 'Punjab' },
    { name: 'Madurai', state: 'Tamil Nadu' },
    { name: 'Mangalore', state: 'Karnataka' },
    { name: 'Meerut', state: 'Uttar Pradesh' },
    { name: 'Moradabad', state: 'Uttar Pradesh' },
    { name: 'Mumbai', state: 'Maharashtra' },
    { name: 'Mysore', state: 'Karnataka' },
    { name: 'Nagpur', state: 'Maharashtra' },
    { name: 'Nashik', state: 'Maharashtra' },
    { name: 'Navi Mumbai', state: 'Maharashtra' },
    { name: 'Noida', state: 'Uttar Pradesh' },
    { name: 'Patna', state: 'Bihar' },
    { name: 'Pune', state: 'Maharashtra' },
    { name: 'Raipur', state: 'Chhattisgarh' },
    { name: 'Rajkot', state: 'Gujarat' },
    { name: 'Ranchi', state: 'Jharkhand' },
    { name: 'Rohtak', state: 'Haryana' },
    { name: 'Rourkela', state: 'Odisha' },
    { name: 'Salem', state: 'Tamil Nadu' },
    { name: 'Siliguri', state: 'West Bengal' },
    { name: 'Solapur', state: 'Maharashtra' },
    { name: 'Surat', state: 'Gujarat' },
    { name: 'Thane', state: 'Maharashtra' },
    { name: 'Thiruvananthapuram', state: 'Kerala' },
    { name: 'Tiruchirappalli', state: 'Tamil Nadu' },
    { name: 'Udaipur', state: 'Rajasthan' },
    { name: 'Ujjain', state: 'Madhya Pradesh' },
    { name: 'Vadodara', state: 'Gujarat' },
    { name: 'Varanasi', state: 'Uttar Pradesh' },
    { name: 'Vijayawada', state: 'Andhra Pradesh' },
    { name: 'Visakhapatnam', state: 'Andhra Pradesh' },
    { name: 'Warangal', state: 'Telangana' },
];
